# Generated by Django 5.1 on 2024-08-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
        ('turmas', '0012_alter_turma_container'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do diretório')),
                ('container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='turmas.containerturma')),
                ('pai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documento.diretorio')),
            ],
        ),
    ]
