# Generated by Django 5.1 on 2024-08-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0004_documento_diretorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='diretorio',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='turma',
        ),
    ]
