# Generated by Django 5.1 on 2024-08-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0005_remove_documento_diretorio_remove_documento_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='documento',
        ),
        migrations.AddField(
            model_name='documento',
            name='caminho',
            field=models.CharField(max_length=256, null=True, verbose_name='Caminho do documento'),
        ),
    ]
