- name: Roda container existente
  hosts: jupyflow
  vars:
    nome_container: "{{ nome_container }}"

  tasks:
    - name: Run jupyterhub docker container
      command: "docker start {{ nome_container }}"

