---
- name: Install jupyterhub docker
  hosts: jupyflow
  vars:
    port_extenal: "{{ port_external }}"
    port_docker: 8003
    name_container: "{{ tag_container }}"
  become: yes

  
  tasks:
    - name: Execute docker login
      command: docker login --username=comaisuft --password-stdin
      args:
        stdin: "srcomais01"

    - name: Pull 3b docker image
      command: docker pull comaisuft/jupyflow:latest

    - name: Create jupyterhub docker container
      command: "docker run -d -e TURMA='/{{name_container}}/' --name {{name_container}} -p {{port_extenal}}:{{port_docker}} comaisuft/jupyflow:latest"

    - name: Adicionar usuário no container
      community.docker.docker_container_exec:
       container: "{{name_container}}"
       command: /bin/bash -c 'useradd  -s /bin/bash -m -r -p $(openssl passwd -1 {{item.password}}) {{item.user}}'
       chdir: /root
      loop:
        "{{ users }}"

    - name: Atualizar PATH
      community.docker.docker_container_exec:
        container: "{{ name_container }}"
        user: "{{ item.user }}"
        command: /bin/bash -c 'echo "export PATH=$PATH/home/{{item.user}}/.local/bin" >> /home/{{item.user}}/.bashrc'
        chdir: /home/{{item.user}}
      loop:
        "{{ users }}"

    - name: Configura HAProxy
      template:
        src: ../base_files/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - restart haproxy

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
