---
- name: Install jupyterhub docker
  hosts: jupyflow
  vars:
    port_extenal: "{{ port_external }}"
    port_docker: 8000
    name_container: "{{ tag_container }}"
  become: yes

  
  tasks:
    - name: Execute docker login
      command: docker login --username=comaisuft --password-stdin
      args:
        stdin: "srcomais01"

    - name: Pull 3b docker image
      command: docker pull comaisuft/jupyflow:latest
    - name: Create jupyterhub docker container
      command: "docker run -d --name {{name_container}} -p {{port_extenal}}:{{port_docker}} comaisuft/jupyflow:latest"
    #install haproxy
    # - name: Install haproxy
    #   apt:
    #     name: haproxy
    #     state: present  
    # - name: Install haproxy
    #   apt:
    #     name: haproxy
    #     state: present  
    # - name: "starting haproxy services"
    #   service:
    #     name: "haproxy"
    #     state: started

    #- name: Enable server in 'www' backend pool
    #  community.general.haproxy:
    #   state: enabled
    #   host: jupyflow
     #  backend: 192.168.0.8:8002

    - name: Adicionar usuário no container
      community.docker.docker_container_exec:
       container: "{{name_container}}"
       command: /bin/bash -c 'useradd  -s /bin/bash -m -r -p $(openssl passwd -1 {{item.password}}) {{item.user}}'
       chdir: /root
      loop:
        "{{ users }}"
      register: result


    - name: Print stdout
      ansible.builtin.debug:
        var: result.stdout  

    - name: Atualizar PATH
      community.docker.docker_container_exec:
       container: "{{name_container}}"
       user: "{{item.user}}"
       #atualiza o PATH para incluir o diretório .local/bin
       command: /bin/bash -c 'echo "export PATH=$PATH:/home/{{item.user}}/.local/bin" >> /home/{{item.user}}/.bashrc'
       chdir: /home/{{item.user}} 
      loop:
        "{{ users }}"
      register: result

    #- name: Print stdout
    #  ansible.builtin.debug:
    #    var: result.stdout
      