# Generated by Django 5.0.6 on 2024-05-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=200, verbose_name='Nome do curso')),
                ('nome_turma', models.CharField(max_length=200, verbose_name='Nome da Turma')),
                ('tag_turma', models.CharField(max_length=20, verbose_name='Tag do Container')),
                ('alunos', models.JSONField(default=None, null=True, verbose_name='Lista de alunos')),
            ],
        ),
    ]
