# Generated by Django 5.0.6 on 2024-05-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='tag_turma',
            field=models.CharField(max_length=20, unique=True, verbose_name='Tag do Container'),
        ),
    ]
