# Generated by Django 5.0.6 on 2024-05-16 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_alter_turma_tag_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_container', models.CharField(max_length=20, unique=True, verbose_name='Tag do Container')),
                ('ativo', models.CharField(default=False, verbose_name='Ativo')),
            ],
        ),
        migrations.RemoveField(
            model_name='turma',
            name='tag_turma',
        ),
        migrations.AddField(
            model_name='turma',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turmas.containerturma'),
        ),
    ]
