# Generated by Django 5.0.6 on 2024-05-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0006_aluno_ultimaporta_remove_turma_alunos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='senha',
            field=models.CharField(max_length=200, verbose_name='Senha do Aluno'),
        ),
    ]
