# Generated by Django 5.0.6 on 2024-07-23 20:45

import django.db.models.deletion
import turmas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0008_aluno_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do documento')),
                ('documento', models.FileField(upload_to=turmas.models.upload_documento)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma')),
            ],
        ),
    ]
