# Generated by Django 5.1 on 2024-08-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0009_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerturma',
            name='ansible_log',
        ),
        migrations.AddField(
            model_name='containerturma',
            name='mensagem_erro',
            field=models.TextField(null=True, verbose_name='Mensagem de Erro'),
        ),
    ]
