# Generated by Django 5.1 on 2024-08-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0010_remove_containerturma_ansible_log_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
