# Generated by Django 5.1 on 2024-08-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0011_delete_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='container',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='turmas.containerturma'),
        ),
    ]
